export default [
    // tokens básicos
    { nome: 'STRING', variacoes: [], descricao: 'um <span class="identificador">texto</span>' },
    { nome: 'NUMBER', variacoes: [], descricao: 'um <span class="identificador">número</span>' },
    { nome: 'IDENTIFICATOR', variacoes: [], descricao: 'um <span class="identificador">identificador</span>' },
    {
        nome: 'BOOLEAN',
        variacoes: ['true', 'false', 'verdadeiro', 'falso', 'verdade', 'mentira'],
        descricao: 'um valor <span class="identificador">lógico</span>',
    },
    { nome: 'NULL', variacoes: ['null', 'nulo'], descricao: 'um valor <span class="identificador">nulo</span>' },

    // palavras reservadas
    { nome: 'ASSIGN', variacoes: ['recebe'], descricao: 'palavra "<span class="palavra-chave">recebe</span>"' },
    { nome: 'BREAK', variacoes: ['break', 'pare'], descricao: 'palavra "<span class="palavra-chave">pare</span>"' },
    { nome: 'CASE', variacoes: ['caso', 'case'], descricao: 'palavra "<span class="palavra-chave">continue</span>"' },
    {
        nome: 'CONST',
        variacoes: ['const', 'constante'],
        descricao: 'palavra "<span class="palavra-chave">const</span>"',
    },
    { nome: 'CONTINUE', variacoes: ['continue'], descricao: 'palavra "<span class="palavra-chave">continue</span>"' },
    {
        nome: 'DEFAULT',
        variacoes: ['default', 'padrao', 'padrão'],
        descricao: 'palavra "<span class="palavra-chave">igual</span>"',
    },
    { nome: 'DO', variacoes: ['do', 'faça', 'faca'], descricao: 'palavra "<span class="palavra-chave">faca</span>"' },
    { nome: 'FROM', variacoes: ['de', 'from'], descricao: 'palavra "<span class="palavra-chave">de</span>"' },
    {
        nome: 'ELSE',
        variacoes: ['else', 'senão', 'senao'],
        descricao: 'palavra "<span class="palavra-chave">senao</span>"',
    },
    { nome: 'EQUAL', variacoes: ['igual'], descricao: 'palavra "<span class="palavra-chave">igual</span>"' },
    { nome: 'FOR', variacoes: ['for', 'para'], descricao: 'palavra "<span class="palavra-chave">para</span>"' },
    { nome: 'FOREACH', variacoes: ['foreach', 'cada'], descricao: 'palavra "<span class="palavra-chave">cada</span>"' },
    {
        nome: 'FUNCTION',
        variacoes: ['function', 'funcao', 'função'],
        descricao: 'palavra "<span class="palavra-chave">funcao</span>"',
    },
    { nome: 'IF', variacoes: ['if', 'se'], descricao: 'palavra "<span class="palavra-chave">se</span>"' },
    { nome: 'IN', variacoes: ['in', 'em'], descricao: 'palavra "<span class="palavra-chave">em</span>"' },
    {
        nome: 'THEN',
        variacoes: ['then', 'então', 'entao'],
        descricao: 'palavra "<span class="palavra-chave">entao</span>"',
    },
    { nome: 'TO', variacoes: ['to', 'ate', 'até'], descricao: 'palavra "<span class="palavra-chave">até</span>"' },
    {
        nome: 'REPEAT',
        variacoes: ['repeat', 'repita'],
        descricao: 'palavra "<span class="palavra-chave">repita</span>"',
    },
    {
        nome: 'RETURN',
        variacoes: ['return', 'retorno'],
        descricao: 'palavra "<span class="palavra-chave">retorno</span>"',
    },
    { nome: 'STEP', variacoes: ['step', 'passo'], descricao: 'palavra "<span class="palavra-chave">passo</span>"' },
    {
        nome: 'SWITCH',
        variacoes: ['switch', 'escolha'],
        descricao: 'palavra "<span class="palavra-chave">igual</span>"',
    },
    {
        nome: 'VAR',
        variacoes: ['var', 'variavel', 'variável'],
        descricao: 'palavra "<span class="palavra-chave">var</span>"',
    },
    {
        nome: 'WHILE',
        variacoes: ['while', 'enquanto'],
        descricao: 'palavra "<span class="palavra-chave">enquanto</span>"',
    },

    // símbolos
    { nome: 'ADD', variacoes: ['+'], descricao: '+' },
    { nome: 'AND', variacoes: ['&&', '&', 'e'], descricao: '&& ou &&' },
    {
        nome: 'ASSIGN',
        variacoes: ['=', '<-', '+=', '-=', '*=', '/=', '%=', '**=', 'recebe'],
        descricao: 'um sinal de "<span class="simbolo">atribuição</span>"',
    },
    { nome: 'CLOSE_CURLY', variacoes: ['}'], descricao: '}' },
    { nome: 'CLOSE_PARENTHESIS', variacoes: [')'], descricao: ')' },
    { nome: 'CLOSE_SQUARE', variacoes: [']'], descricao: ']' },
    { nome: 'COLON', variacoes: [':'], descricao: ':' },
    { nome: 'COMMA', variacoes: [','], descricao: ',' },
    { nome: 'DEC', variacoes: ['--'], descricao: '--' },
    { nome: 'DIV', variacoes: ['/'], descricao: '/' },
    { nome: 'DOT', variacoes: ['.'], descricao: '.' },
    { nome: 'DIFF', variacoes: ['!=', '<>', 'diferente'], descricao: '!= ou <>' },
    { nome: 'EQUAL', variacoes: ['==', '===', 'igual'], descricao: '== ou ===' },
    { nome: 'GT', variacoes: ['>', 'maior'], descricao: '&gt;' },
    { nome: 'GTE', variacoes: ['>=', 'maiorigual'], descricao: '&gte;' },
    { nome: 'INC', variacoes: ['++'], descricao: '++' },
    { nome: 'LT', variacoes: ['<', 'menor'], descricao: '&lt;' },
    { nome: 'LTE', variacoes: ['<=', 'menorigual'], descricao: '&lte;' },
    { nome: 'MOD', variacoes: ['%'], descricao: '%' },
    { nome: 'POW', variacoes: ['**'], descricao: '**' },
    { nome: 'MULT', variacoes: ['*'], descricao: '*' },
    { nome: 'NOT', variacoes: ['!', 'not', 'não', 'nao'], descricao: '!' },
    { nome: 'OR', variacoes: ['||', '!!', 'ou'], descricao: '|| ou !!' },
    { nome: 'OPEN_CURLY', variacoes: ['{'], descricao: '{' },
    { nome: 'OPEN_PARENTHESIS', variacoes: ['('], descricao: '(' },
    { nome: 'OPEN_SQUARE', variacoes: ['['], descricao: '[' },
    { nome: 'SEMICOLON', variacoes: [';'], descricao: ';' },
    { nome: 'SUB', variacoes: ['-'], descricao: '-' },
    { nome: 'QUESTION', variacoes: ['?'], descricao: '?' },
    { nome: 'XOR', variacoes: ['xor', 'xou'], descricao: 'Xou' },
];
